insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(0,'₿','Bitcoin','BTC');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(1,'€','Euro','EUR');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(2,'Ł','Litecoin','LTC');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(3,'£','British Pound','GBP');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(4,'$','United States Dollar','USD');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(5,'Ξ','Ether','ETH');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(6,'Ξ','0x','ZRX');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(7,'₿','Bitcoin Cash','BCH');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(8,'⟠','Ether Classic','ETC');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(9,'$','USD Coin','USDC');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(10,'Ξ','Basic Attention Token','BAT');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(11,'ᙇ','Zcash','ZEC');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(12,'Ξ','Loom Network','LOOM');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(13,'Ξ','Civic','CVC');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(14,'Ξ','district0x','DNT');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(15,'Ξ','Decentraland','MANA');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(16,'Ξ','Golem','GNT');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(17,'Ξ','Dai','DAI');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(18,'Ξ','Maker','MKR');
insert into currency(currency_id, currency_symbol, currency_long_name, currency_short_name) values(19,'Ξ','Zilliqa','ZIL');
